import { faFileImport, faFloppyDisk, faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React from 'react';

export default async function Page() {
      
  return (
    <>
      <div className='content-wrap'>  
        <h1>Welcome to Easy Recipes</h1>

        <p>
          Easy Recipes lets you browse a catalogue of recipes, which have been generated by AI.
          Youtube videos are transcribed using Audio to Text, and fed to a GPT assistant, which
          generates a nicely formatted recipe. 
        </p>
        <p>
          Logged in users can generate recipes by simply 
          copying the video URL and pasting it on the create recipe page.
        </p>

        <p>
          Anyone can browse the recipes, give them a rating, and save them for easy access.
          The site is designed to be simple and to the point, so you can get to cooking and spend
          less time scrolling looking for the ingredients.
        </p>

        <p><em>Click the image below to explore recipes: </em></p>
        <a 
          href='http://localhost:3000/search?query=&start=0' 
          className='example-img' >
          <img src='/images/main1.png' alt='preview' />
        </a>
      </div>
      <div className='span-page-wrap'>
        <ul className='features-list'> 
          <li>
            <span>Convert videos to recipes</span>
            <FontAwesomeIcon icon={faFileImport} />
          </li>
          <li>
            <span>Save your favourite recipes</span>
            <FontAwesomeIcon icon={faFloppyDisk} />
          </li>
          <li>
            <span>Search generated recipes</span>
            <FontAwesomeIcon icon={faMagnifyingGlass} />
          </li>
        </ul>
      </div>
    </>
  );
}
